#!/bin/bash -eux

source "$SNAP_COMPONENTS/llamacpp-amd64v3/server.rc"

exec "$SERVER_PATH" \
  --model "$MODEL_FILE" \
  --mmproj "$MMPROJ_FILE" \
  --port "$PORT" \
  --host "$HOST" \
  "${EXTRA_ARGS[@]}"
