#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
sleep_idle_seconds="$(modelctl get sleep-idle-seconds)"

EXTRA_ARGS=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  EXTRA_ARGS+=(--verbose)
fi

set -x
exec llama-server \
  --model "$MODEL_FILE" \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  --sleep-idle-seconds "$sleep_idle_seconds" \
  "${EXTRA_ARGS[@]}" \
  "$@"
