#!/bin/bash -eux

source "$SNAP_COMPONENTS/llamacpp/server.rc"

# The engine must set --mmproj if a multimodal projector is needed

exec "$SERVER_PATH" \
  --model "$MODEL_FILE" \
  --port "$PORT" \
  --host "$HOST" \
  "${EXTRA_ARGS[@]}" \
  "$@"
