#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
sleep_idle_seconds="$(modelctl get sleep-idle-seconds)"

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

# The engine must set --mmproj if a multimodal projector is needed

set -x
exec llama-server \
  --model "$MODEL_FILE" \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  --sleep-idle-seconds "$sleep_idle_seconds"
  "${extra_args[@]}" \
  "$@"
