#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"

model_file="$MODEL_FILE"

model="$(modelctl get --engine model)" # equivalent to `modelctl get engine.<engine>.model`
# If value is an absolute path, use it to override global model file path
if [[ "$model" = /* ]]; then
  model_file="$model"
fi

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

# The engine must set --mmproj if a multimodal projector is needed

set -x
exec llama-server \
  --model "$model_file" \
  --port "$port" \
  --host "$host" \
  "${extra_args[@]}" \
  "$@"
