name: gemma3

on:
  # Label trigger on PRs
  pull_request:
    types: [ labeled ]

jobs:
  remove-test-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@v2
    with:
      label: ${{ vars.PR_BUILD_TRIGGER_LABEL }}
      
  prepare-tests:
    name: Prepare tests
    if: (github.event.action == 'labeled' && github.event.label.name == '${{ vars.PR_TRIGGER_TESTS_LABEL }}')
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.prepare.outputs.build-success }}
      snap-channel: ${{ steps.prepare.outputs.snap-channel }}
    steps:
      - id: prepare
        name: Resolve test channel and check for successful build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # exit with non-zero code if any command fails, if any variable is unset, or if any command in a pipeline fails
          set -euo pipefail

          commit_sha="${{ github.event.pull_request.head.sha }}"
          successful_runs_count="$(gh run list --repo "${{ github.repository }}" --commit "$commit_sha" --json conclusion,workflowName --jq '[.[] | select(.conclusion == "success" and .workflowName == "Build PR when labeled")] | length')"

          if [ "$successful_runs_count" -gt 0 ]; then
            echo "Found successful run(s) for commit $commit_sha"
            echo "build-success=true" >> "$GITHUB_OUTPUT"
          else
            echo "No successful runs found for commit $commit_sha"
            echo "build-success=false" >> "$GITHUB_OUTPUT"
          fi

          echo "snap-channel=latest/edge/pr-${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"

  trigger-pr-build:
    name: Trigger PR build when missing
    needs:
      - prepare-tests
    if: needs.prepare-tests.outputs.build-success == 'false'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add build trigger label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --repo "${{ github.repository }}" \
            --add-label "${{ vars.PR_BUILD_TRIGGER_LABEL }}"

  # test-multimodal-prompt:
  #   needs:
  #     - prepare-tests
  #   name: gemma3 ${{ matrix.jobs.select-engine }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       jobs:
  #         - job-queue: maas-systemtests-amd64
  #           provision-data: "distro: noble"
  #           select-engine: cpu
  #           test-chat-tps: true
  #           test-image-prompt: true

  #         - job-queue: mir-intel-noble
  #           provision-data: "distro: noble"
  #           select-engine: intel-cpu
  #           test-chat-tps: true
  #           test-image-prompt: true

  #         - job-queue: 202111-29603 # Alder Lake, GPU 8086:4680
  #           provision-data: "distro: noble"
  #           select-engine: intel-gpu
  #           test-chat-tps: true
  #           test-image-prompt: true

  #         - job-queue: anbox-nvidia-amd64
  #           provision-data: "distro: noble"
  #           install-nvidia-driver-version: 550
  #           select-engine: nvidia-gpu-amd64
  #           test-chat-tps: true
  #           expected-tps: 10
  #           test-image-prompt: true

  #         # Skip nvidia-gpu-arm64 engine as we do not have a test machine for it

  #         - job-queue: 202203-30094 # Core-i7-12850HX + Radeon PRO W6600M
  #           provision-data: "distro: noble"
  #           snap-connections: "process-control"
  #           select-engine: amd-gpu
  #           test-chat-tps: true
  #           expected-tps: 10
  #           test-image-prompt: true

  #         - job-queue: maas-systemtests-amd64
  #           provision-data: "distro: noble"
  #           select-engine: cpu-xsmall
  #           test-chat-tps: true
  #           test-image-prompt: false # cpu-xsmall engine does not support image input

  #   uses: canonical/inference-snaps-testing/.github/workflows/test-snap.yaml@main
  #   secrets: inherit
  #   with:
  #     job-queue: ${{ matrix.jobs.job-queue }}
  #     provision-data: ${{ matrix.jobs.provision-data }}

  #     snap-name: gemma3
  #     snap-channel: ${{ needs.prepare-tests.outputs.snap-channel }}

  #     install-nvidia-driver-version: ${{ matrix.jobs.install-nvidia-driver-version }}
  #     install-intel-npu-driver: ${{ matrix.jobs.install-intel-npu-driver == true }}
  #     snap-connections: ${{ matrix.jobs.snap-connections }}

  #     expected-engine: ${{ matrix.jobs.expected-engine }}
  #     select-engine: ${{ matrix.jobs.select-engine }}

  #     test-chat-tps: ${{ matrix.jobs.test-chat-tps == true }}
  #     expected-tps: ${{ matrix.jobs.expected-tps }}

  #     test-image-prompt: ${{ matrix.jobs.test-image-prompt == true }}