#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.post-refresh"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

# Symlink /var/lib/snapd/hostfs/usr/lib/wsl to $SNAP_COMMON/usr/lib/wsl so that layout can bind it to /usr/lib/wsl
mkdir -p $SNAP_COMMON/usr/lib
# Remove existing directory if present, so symlink can replace it
rm -rf $SNAP_COMMON/usr/lib/wsl
ln -s /var/lib/snapd/hostfs/usr/lib/wsl $SNAP_COMMON/usr/lib/

# Refresh the active engine
# This involves applying changes to configurations and required snap components.
# If the active engine has been removed, another engine will be auto selected.
# The automatic selection requires access to hardware information on the system.
if snapctl is-connected hardware-observe; then
    modelctl use-engine --fix --assume-yes
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    modelctl use-engine --fix --assume-yes
else
    echo "hardware-observe interface not connected. Skip fixing the active engine."
fi
